version: '2'

volumes: 
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: always
    network_mode: host
    volumes:
      - '$HOME/assingments/Sigmoid_Assingment/prometheus-assignment/prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana
    restart: always
    network_mode: host
    depends_on:
      - prometheus
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
      - ./config.ini:/etc/grafana/grafana.ini

